### ISSUE TITLE
[About page] Populate board members through API

### ISSUE THREAD

**Issue by ashleytqy** [TechAtNYU/techatnyu.org-2018#6]
by 28th September

**Comment by ashleytqy** [comment]
Maybe a to-do in the future, right now the hard coded data works.

**Comment by brentdur** [comment]
This should be pretty easy to implement given that the code is used already on the eboard page on blueprint. Regardless let's leave this open til it's done (but maybe unassign if you don't want someone working on it rn)

**Comment by ashleytqy** [comment]
@brentdur right now to get the team member's name via the People resource, we need to be authenticated. (Membership returns links to Position and People resource, and we get) should we stick to the hardcoded data?

@ml4963 

```
The resource at /v3/people is protected. You can start a facebook oAuth sign-in at: https://api.tnyu.org/v3/auth/facebook
```

**Comment by brentdur** [comment]
A good way of doing this may be to have a json file with a limited set of
the person data (just the fields we need like name, picture, position) that
the JavaScript uses. Then have a circleCI job that pulls this data at some
interval and uploads the file to the site. I think this will work as the
board member positions don’t change super frequently / when they do it
isn’t time sensitive to update and this still allows everything to link
back to the api as the source of truth. So maybe pull the data manually
into a json file using the blueprint endpoint, strip out the data we don’t
need and save it into a json file and we can use that as our template for
the ci job later

**Comment by ethanresnick** [comment]
Simpler: take advantage of the `?include` parameter to join in the members. (Each people object will still be processed by the api to filter out sensitive fields.) That endpoint is:

```
https://api.tnyu.org/v3/memberships?include=member,position
```

Should give you everything you need with no auth.

**Comment by ashleytqy** [comment]
Fixed: https://github.com/TechAtNYU/techatnyu.org/pull/13
